### ISSUE TITLE
https://musicaldown.com/en/ is your website?

### ISSUE THREAD

**Issue by Al-Iverson** [majhcc/M-API#2]
https://musicaldown.com/en/ is your website?   if not, this way will be stopped at any time.

**Comment by majhcc** [comment]
It is not my website, and if that happens I'll use new website.

**Comment by majhcc** [comment]
Here there are many provides that you can use them https://github.com/hansputera/tiktok-dl/tree/dev/packages/core/src

**Comment by Al-Iverson** [comment]
Thanks Reply. i want to know the limits of this api. is there such a limit?

**Comment by majhcc** [comment]
I didn't set a limit for TikTok api, also you can make a api like this using Heroku. However, there are limiting from heroku 4500 request in the hours. Thanks

**Comment by Al-Iverson** [comment]
ok fine. i find other way also can convert tiktok video.i will use several way to convert tiktok link. thank you very much for your reply.
